name: Zip on major release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: zip extension
        run: zip -r DownQ.zip . -x "*.git" - x "*.github"

      - name: "publish release"
        uses: softprops/action-gh-release@v1
        with:
          files: DownQ.zip
          tag_name: ${{ github.ref_name || 'manual-build' }}